name: Avytage-Shop
favicon: null
layout_spectrum: 0.08507425780408084
typography_spectrum: 0.944496241863817
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.15151542401872575
  lightness: 0.8862881432287395
  saturation: 0.6023735422641039
  rhythmicContrast: 0.9968559078406543
purpose: []
